Update lagoonize.md
If choose [drupal8-composer-mariadb](https://github.com/amazeeio/lagoon/tree/master/docs/using_lagoon/drupal/drupal8-composer-mariadb) to set up, It will fail on `docker-compose build`  because of no patches dir is there.

```
docker-compose build
mariadb uses an image, skipping
redis uses an image, skipping
varnish uses an image, skipping
Building cli
Step 1/7 : FROM amazeeio/php:7.1-cli-drupal
 ---> 543ef51953cd
Step 2/7 : COPY composer.json composer.lock /app/
 ---> Using cache
 ---> 9060beb3a814
Step 3/7 : COPY scripts /app/scripts
 ---> Using cache
 ---> b931273f117a
Step 4/7 : COPY patches /app/patches
ERROR: Service 'cli' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder271689484/patches: no such file or directory
```